language: node_js
node_js:
    - "6.1.0"
before_script:
    - npm install
env:
  - NODE_ENV=development
script:
    - npm run dist
    - npm run test
    - npm run lint
notifications:
  slack:
    on_pull_requests: false
notifications:
  slack:
    on_pull_requests: false
    rooms:
      - cejs-atsistemas:M6CFKRntBzELQ8smobHlwnDa#angular-base
