export const AccountActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',

  GET_CURRENTUSER_REQUEST: 'GET_CURRENTUSER_REQUEST',
  GET_CURRENTUSER_SUCCESS: 'GET_CURRENTUSER_SUCCESS',
  GET_CURRENTUSER_ERROR: 'GET_CURRENTUSER_ERROR',


  GET_BILLINGCODELIST_REQUEST: 'GET_BILLINGCODELIST_REQUEST',
  GET_BILLINGCODELIST_SUCCESS: 'GET_BILLINGCODELIST_SUCCESS',
  GET_BILLINGCODELIST_ERROR: 'GET_BILLINGCODELIST_ERROR',
};
