import { createActionType } from 'base';

export const ActionTypes = createActionType([
  'WEATHERSTATIONS_REQUEST',
  'WEATHERSTATIONS_SUCCESS',
  'WEATHERSTATIONS_ERROR',  
  'WEATHERSTATION_REQUEST',
  'WEATHERSTATION_SUCCESS',
  'WEATHERSTATION_ERROR',
  'WEATHERSTATION_SELECTED',
  'FORECAST_REQUEST',
  'FORECAST_SUCCESS',
  'FORECAST_ERROR',

  'MAINB_REQUEST',
  'MAINB_SUCCESS',
  'MAINB_ERROR',
]);

