export const actionTypes = {
    CLICK:          'CLICK',
    MAIN_CONTAINER: 'MAIN_CONTAINER',
    MAIN_REQUEST:   'MAIN_REQUEST',
    MAIN_SUCCESS:   'MAIN_SUCCESS',
    MAIN_ERROR:     'MAIN_ERROR',
    LAZY_CONTAINER: 'LAZY_CONTAINER'
}