export const ActionTypes = {
  CLICK:          'CLICK',
  MAIN_CONTAINER: 'MAIN_CONTAINER',
  MAIN_ERROR:     'MAIN_ERROR',
  MAIN_REQUEST:   'MAIN_REQUEST',
  MAIN_SUCCESS:   'MAIN_SUCCESS',
  LAZY_CONTAINER: 'LAZY_CONTAINER',
  LOGIN:   'LOGIN',
};
